--
--    COPYRIGHT 2016 THE ORIGINAL AUTHOR OR AUTHORS.
--
--    LICENSED UNDER THE APACHE LICENSE, VERSION 2.0 (THE "LICENSE");
--    YOU MAY NOT USE THIS FILE EXCEPT IN COMPLIANCE WITH THE LICENSE.
--    YOU MAY OBTAIN A COPY OF THE LICENSE AT
--
--       HTTP://WWW.APACHE.ORG/LICENSES/LICENSE-2.0
--
--    UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN WRITING, SOFTWARE
--    DISTRIBUTED UNDER THE LICENSE IS DISTRIBUTED ON AN "AS IS" BASIS,
--    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED.
--    SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS AND
--    LIMITATIONS UNDER THE LICENSE.
--

CREATE TABLE SUPPLIER (
    SUPPID INT NOT NULL,
    NAME VARCHAR(80) NULL,
    STATUS VARCHAR(2) NOT NULL,
    ADDR1 VARCHAR(80) NULL,
    ADDR2 VARCHAR(80) NULL,
    CITY VARCHAR(80) NULL,
    STATE VARCHAR(80) NULL,
    ZIP VARCHAR(5) NULL,
    PHONE VARCHAR(80) NULL,
    CONSTRAINT PK_SUPPLIER PRIMARY KEY (SUPPID)
);

CREATE TABLE SIGNON (
    USERNAME VARCHAR(25) NOT NULL,
    PASSWORD VARCHAR(80)  NOT NULL,
    CONSTRAINT PK_SIGNON PRIMARY KEY (USERNAME)
);

CREATE TABLE ACCOUNT (
    USERID VARCHAR(80) NOT NULL,
    EMAIL VARCHAR(80) NOT NULL,
    FIRSTNAME VARCHAR(80) NOT NULL,
    LASTNAME VARCHAR(80) NOT NULL,
    STATUS VARCHAR(2)  NULL,
    ADDR1 VARCHAR(80) NOT NULL,
    ADDR2 VARCHAR(40) NULL,
    CITY VARCHAR(80) NOT  NULL,
    STATE VARCHAR(80) NOT NULL,
    ZIP VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(20) NOT NULL,
    PHONE VARCHAR(80) NOT NULL,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (USERID)
);

CREATE TABLE PROFILE (
    USERID VARCHAR(80) NOT NULL,
    LANGPREF VARCHAR(80) NOT NULL,
    FAVCATEGORY VARCHAR(30),
    MYLISTOPT INT,
    BANNEROPT INT,
    CONSTRAINT PK_PROFILE PRIMARY KEY (USERID)
);

CREATE TABLE BANNERDATA (
    FAVCATEGORY VARCHAR(80) NOT NULL,
    BANNERNAME VARCHAR(255)  NULL,
    CONSTRAINT PK_BANNERDATA PRIMARY KEY (FAVCATEGORY)
);

CREATE TABLE ORDERS (
    ORDERID INT NOT NULL,
    USERID VARCHAR(80) NOT NULL,
    ORDERDATE TIMESTAMP NOT NULL,
    SHIPADDR1 VARCHAR(80) NOT NULL,
    SHIPADDR2 VARCHAR(80) NULL,
    SHIPCITY VARCHAR(80) NOT NULL,
    SHIPSTATE VARCHAR(80) NOT NULL,
    SHIPZIP VARCHAR(20) NOT NULL,
    SHIPCOUNTRY VARCHAR(20) NOT NULL,
    BILLADDR1 VARCHAR(80) NOT NULL,
    BILLADDR2 VARCHAR(80)  NULL,
    BILLCITY VARCHAR(80) NOT NULL,
    BILLSTATE VARCHAR(80) NOT NULL,
    BILLZIP VARCHAR(20) NOT NULL,
    BILLCOUNTRY VARCHAR(20) NOT NULL,
    COURIER VARCHAR(80) NOT NULL,
    TOTALPRICE DECIMAL(10,2) NOT NULL,
    BILLTOFIRSTNAME VARCHAR(80) NOT NULL,
    BILLTOLASTNAME VARCHAR(80) NOT NULL,
    SHIPTOFIRSTNAME VARCHAR(80) NOT NULL,
    SHIPTOLASTNAME VARCHAR(80) NOT NULL,
    CREDITCARD VARCHAR(80) NOT NULL,
    EXPRDATE VARCHAR(7) NOT NULL,
    CARDTYPE VARCHAR(80) NOT NULL,
    LOCALE VARCHAR(80) NOT NULL,
    CONSTRAINT PK_ORDERS PRIMARY KEY (ORDERID)
);

CREATE TABLE ORDERSTATUS (
    ORDERID INT NOT NULL,
    LINENUM INT NOT NULL,
    TIMESTAMP DATE NOT NULL,
    STATUS VARCHAR(2) NOT NULL,
    CONSTRAINT PK_ORDERSTATUS PRIMARY KEY (ORDERID, LINENUM)
);

CREATE TABLE ORDERLINES (
    ORDERID INT NOT NULL,
    LINENUM INT NOT NULL,
    ITEMID VARCHAR(10) NOT NULL,
    QUANTITY INT NOT NULL,
    UNITPRICE DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_LINEITEM PRIMARY KEY (ORDERID, LINENUM)
);

CREATE TABLE CATEGORY (
    CATID VARCHAR(10) NOT NULL,
    NAME VARCHAR(80) NULL,
    DESCN VARCHAR(255) NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATID)
);

CREATE TABLE PRODUCT (
    PRODUCTID VARCHAR(10) NOT NULL,
    CATEGORY VARCHAR(10) NOT NULL,
    NAME VARCHAR(80) NULL,
    DESCN VARCHAR(255) NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (PRODUCTID),
        CONSTRAINT FK_PRODUCT_1 FOREIGN KEY (CATEGORY)
        REFERENCES CATEGORY (CATID)
);

CREATE INDEX PRODUCTCAT ON PRODUCT (CATEGORY);
CREATE INDEX PRODUCTNAME ON PRODUCT (NAME);

CREATE TABLE ITEM (
    ITEMID VARCHAR(10) NOT NULL,
    PRODUCTID VARCHAR(10) NOT NULL,
    LISTPRICE DECIMAL(10,2) NULL,
    UNITCOST DECIMAL(10,2) NULL,
    SUPPLIER INT NULL,
    STATUS VARCHAR(2) NULL,
    ATTR1 VARCHAR(80) NULL,
    ATTR2 VARCHAR(80) NULL,
    ATTR3 VARCHAR(80) NULL,
    ATTR4 VARCHAR(80) NULL,
    ATTR5 VARCHAR(80) NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY (ITEMID),
        CONSTRAINT FK_ITEM_1 FOREIGN KEY (PRODUCTID)
        REFERENCES PRODUCT (PRODUCTID),
        CONSTRAINT FK_ITEM_2 FOREIGN KEY (SUPPLIER)
        REFERENCES SUPPLIER (SUPPID)
);

CREATE INDEX ITEMPROD ON ITEM (PRODUCTID);

CREATE TABLE INVENTORY (
    ITEMID VARCHAR(10) NOT NULL,
    QTY INT NOT NULL,
    CONSTRAINT PK_INVENTORY PRIMARY KEY (ITEMID)
);

CREATE TABLE SEQUENCE(
    NAME               VARCHAR(30)  NOT NULL,
    NEXTID             INT          NOT NULL,
    CONSTRAINT PK_SEQUENCE PRIMARY KEY (NAME)
);
